# Generated by Django 2.2.5 on 2019-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roks',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='uczelnia',
            name='nazwa',
            field=models.CharField(max_length=30, verbose_name='uczelnia'),
        ),
    ]
